module Stories.Button.Primary exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Ui.Button exposing (..)
import Ui.Button
import Storybook.Story exposing (Story)
import Html exposing (Html)

type Msg
    = UserClickedSignUp

main : Story () Msg
main =
    Storybook.Story.stateless
        { view = view
        }
view : Html Msg
view =
    Ui.Button.new { label = "Sign up" }
        |> Ui.Button.onClick UserClickedSignUp
        |> Ui.Button.view

spec0 : Test.Test
spec0 =
    Test.test "#view: \n\n    main\n    --> main" <|
        \() ->
            Expect.equal
                (
                main
                )
                (
                main
                )
